name: sysoracle
channels:
  - conda-forge
  - defaults
dependencies:
  # --- CORE RUNTIME ---
  - python=3.10
  
  # --- C++ TOOLCHAIN & SYSTEMS STUFF ---
  - clangdev         # The C++ compiler (clang++)
  - libcxx           # macOS C++ standard library headers
  - make             # To automate your build commands
  - pkg-config       # Helps the compiler find libcurl/libproc
  
  # --- C++ EXTERNAL LIBRARIES ---
  - curl             # The 'libcurl' headers and binaries for POSTing data
  
  # --- PYTHON BACKEND STUFF ---
  - pip:
      - -r requirements.txt