name: sysoracle
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2025.12.2=hca03da5_0
  - clang=20.1.8=default_h1eedb11_0
  - clang-20=20.1.8=default_h649e436_0
  - clang-format=20.1.8=default_h649e436_0
  - clang-format-20=20.1.8=default_h649e436_0
  - clang-tools=20.1.8=default_h649e436_0
  - clangdev=20.1.8=default_h649e436_0
  - clangxx=20.1.8=default_h0dcb199_0
  - cmake=3.31.1=h326f17c_0
  - expat=2.7.3=h50f4ffc_4
  - icu=73.2=hc8870d7_0
  - krb5=1.21.3=h237132a_0
  - libclang=20.1.8=default_h649e436_0
  - libclang-cpp=20.1.8=default_h649e436_0
  - libclang-cpp20.1=20.1.8=default_h649e436_0
  - libclang13=20.1.8=default_h91d7d2a_0
  - libcurl=8.17.0=hdece5d2_1
  - libcxx=20.1.8=hd7fd590_1
  - libcxx-devel=20.1.8=h6dc3340_3
  - libcxx-headers=20.1.8=h707e725_3
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libiconv=1.18=h23cfdf5_2
  - libllvm20=20.1.8=h846d351_0
  - libnghttp2=1.67.0=hc438710_0
  - libssh2=1.11.1=h1590b86_0
  - libuv=1.51.0=h6caf38d_1
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-tools=20.1.8=hc7d33da_0
  - llvm-tools-20=20.1.8=hb8bff50_0
  - llvmdev=20.1.8=hb8bff50_0
  - make=4.4.1=hc9fafa5_2
  - ncurses=6.5=hee39554_0
  - openssl=3.6.0=h5503f6c_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=hf701271_0
  - readline=8.3=h0b18652_0
  - rhash=1.4.5=h7ab814d_0
  - setuptools=80.9.0=py310hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=hbf9d68e_6
prefix: /opt/anaconda3/envs/sysoracle
